/* Generated By:JavaCC: Do not edit this line. danlopConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface danlopConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int OPEN_CURLY = 11;
  /** RegularExpression Id. */
  int CLOSE_CURLY = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int OPEN_PAREN = 14;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int OBJECT = 19;
  /** RegularExpression Id. */
  int LIST = 20;
  /** RegularExpression Id. */
  int OPERATOR = 21;
  /** RegularExpression Id. */
  int ASSIGN = 22;
  /** RegularExpression Id. */
  int ERROR = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<DIGIT>",
    "<INTEGER>",
    "<FLOAT>",
    "\"if\"",
    "\"while\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<BOOLEAN>",
    "<IDENTIFIER>",
    "<STRING>",
    "<OBJECT>",
    "<LIST>",
    "<OPERATOR>",
    "\"=\"",
    "<ERROR>",
  };

}
